name: engine_auth
description: Engine Auth
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: 0.18.2
  google_sign_in: 4.5.6

  engine_db_utils:
    git: git@bitbucket.org:firebuzz_engine/engine_db_utils.git
  engine_utils:
    git: git@bitbucket.org:firebuzz_engine/engine_utils.git



#  engine_db_utils:
#    path: ../engine_db_utils
#  engine_utils:
#    path: ../engine_utils


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

